version: '3'

services:
  app:
    image: regis:latest
    container_name: regis-app
    ports:
      - "8080:8524"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/userRegister
      - SPRING_DATASOURCE_USERNAME=${USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: userRegister
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
