name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{PASSWORD}}
          MYSQL_DATABASE: userRegister
        ports:
          - 3306:3306 

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"127.0.0.1" --silent; do
            echo 'waiting for mysql to be connectable...'
            sleep 5
          done
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/userRegister
          SPRING_DATASOURCE_USERNAME: ${{USERNAME}}
          SPRING_DATASOURCE_PASSWORD: ${{PASSWORD}}


