name: Workflow 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Update to Node.js 20 compatible version
      - name: Set up JDK 18
        uses: actions/setup-java@v4  # Update to Node.js 20 compatible version
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -DskipTest

